-- Survey store names (Division 701 FM name/number list) + store-aware question text
ALTER TABLE survey_store_districts ADD COLUMN IF NOT EXISTS store_name TEXT;

UPDATE survey_store_districts SET store_name = 'Albany' WHERE store_num = 5;
UPDATE survey_store_districts SET store_name = 'Anchorage-Northern Lights' WHERE store_num = 11;
UPDATE survey_store_districts SET store_name = 'Shoreline (Aurora)' WHERE store_num = 13;
UPDATE survey_store_districts SET store_name = 'Soldotna' WHERE store_num = 17;
UPDATE survey_store_districts SET store_name = 'Muldoon' WHERE store_num = 18;
UPDATE survey_store_districts SET store_name = 'Auburn' WHERE store_num = 19;
UPDATE survey_store_districts SET store_name = 'Bend' WHERE store_num = 21;
UPDATE survey_store_districts SET store_name = 'Bellevue' WHERE store_num = 23;
UPDATE survey_store_districts SET store_name = 'Burlington' WHERE store_num = 24;
UPDATE survey_store_districts SET store_name = 'Bellingham' WHERE store_num = 25;
UPDATE survey_store_districts SET store_name = 'Burien' WHERE store_num = 28;
UPDATE survey_store_districts SET store_name = 'Brookings' WHERE store_num = 30;
UPDATE survey_store_districts SET store_name = 'Benson Plaza' WHERE store_num = 31;
UPDATE survey_store_districts SET store_name = 'Beaverton' WHERE store_num = 35;
UPDATE survey_store_districts SET store_name = 'Burlingame' WHERE store_num = 40;
UPDATE survey_store_districts SET store_name = 'Bonney Lake' WHERE store_num = 41;
UPDATE survey_store_districts SET store_name = 'Coeur d''Alene' WHERE store_num = 49;
UPDATE survey_store_districts SET store_name = 'Coos Bay' WHERE store_num = 50;
UPDATE survey_store_districts SET store_name = 'Covington' WHERE store_num = 53;
UPDATE survey_store_districts SET store_name = 'Cornelius' WHERE store_num = 60;
UPDATE survey_store_districts SET store_name = 'Clackamas' WHERE store_num = 63;
UPDATE survey_store_districts SET store_name = 'Corvallis' WHERE store_num = 70;
UPDATE survey_store_districts SET store_name = 'Dimond' WHERE store_num = 71;
UPDATE survey_store_districts SET store_name = 'Division' WHERE store_num = 75;
UPDATE survey_store_districts SET store_name = 'East Salem' WHERE store_num = 90;
UPDATE survey_store_districts SET store_name = 'Fishers Landing' WHERE store_num = 93;
UPDATE survey_store_districts SET store_name = 'Federal Way' WHERE store_num = 111;
UPDATE survey_store_districts SET store_name = 'Greenwood' WHERE store_num = 122;
UPDATE survey_store_districts SET store_name = 'Glisan' WHERE store_num = 125;
UPDATE survey_store_districts SET store_name = 'Grants Pass' WHERE store_num = 126;
UPDATE survey_store_districts SET store_name = 'Gresham' WHERE store_num = 127;
UPDATE survey_store_districts SET store_name = 'Hawthorne' WHERE store_num = 135;
UPDATE survey_store_districts SET store_name = 'Hazel Dell' WHERE store_num = 140;
UPDATE survey_store_districts SET store_name = 'Hillsboro' WHERE store_num = 143;
UPDATE survey_store_districts SET store_name = 'Interstate' WHERE store_num = 150;
UPDATE survey_store_districts SET store_name = 'Johnson Creek' WHERE store_num = 153;
UPDATE survey_store_districts SET store_name = 'Idaho Falls' WHERE store_num = 156;
UPDATE survey_store_districts SET store_name = 'Juneau' WHERE store_num = 158;
UPDATE survey_store_districts SET store_name = 'Kennewick' WHERE store_num = 163;
UPDATE survey_store_districts SET store_name = 'Klamath Falls' WHERE store_num = 165;
UPDATE survey_store_districts SET store_name = 'Kitsap' WHERE store_num = 171;
UPDATE survey_store_districts SET store_name = 'Lynnwood' WHERE store_num = 180;
UPDATE survey_store_districts SET store_name = 'Longview' WHERE store_num = 185;
UPDATE survey_store_districts SET store_name = 'Lacey' WHERE store_num = 186;
UPDATE survey_store_districts SET store_name = 'North Medford' WHERE store_num = 195;
UPDATE survey_store_districts SET store_name = 'South Medford' WHERE store_num = 196;
UPDATE survey_store_districts SET store_name = 'Meridian' WHERE store_num = 198;
UPDATE survey_store_districts SET store_name = 'Mill Plain' WHERE store_num = 208;
UPDATE survey_store_districts SET store_name = 'Marysville' WHERE store_num = 209;
UPDATE survey_store_districts SET store_name = 'Monroe' WHERE store_num = 210;
UPDATE survey_store_districts SET store_name = 'Wandermere' WHERE store_num = 214;
UPDATE survey_store_districts SET store_name = 'Redondo' WHERE store_num = 215;
UPDATE survey_store_districts SET store_name = 'North Coast' WHERE store_num = 218;
UPDATE survey_store_districts SET store_name = 'Newberg' WHERE store_num = 220;
UPDATE survey_store_districts SET store_name = 'East Fairbanks' WHERE store_num = 224;
UPDATE survey_store_districts SET store_name = 'North Salem' WHERE store_num = 225;
UPDATE survey_store_districts SET store_name = 'Nampa' WHERE store_num = 226;
UPDATE survey_store_districts SET store_name = 'Newport' WHERE store_num = 227;
UPDATE survey_store_districts SET store_name = 'Orchards' WHERE store_num = 236;
UPDATE survey_store_districts SET store_name = 'Oak Grove' WHERE store_num = 240;
UPDATE survey_store_districts SET store_name = 'Oregon City' WHERE store_num = 242;
UPDATE survey_store_districts SET store_name = 'Peninsula' WHERE store_num = 255;
UPDATE survey_store_districts SET store_name = 'Pocatello' WHERE store_num = 260;
UPDATE survey_store_districts SET store_name = 'Puyallup' WHERE store_num = 265;
UPDATE survey_store_districts SET store_name = 'Roseburg' WHERE store_num = 281;
UPDATE survey_store_districts SET store_name = 'Raleigh Hills' WHERE store_num = 285;
UPDATE survey_store_districts SET store_name = 'Richland' WHERE store_num = 286;
UPDATE survey_store_districts SET store_name = 'Santa Clara' WHERE store_num = 325;
UPDATE survey_store_districts SET store_name = 'Springfield' WHERE store_num = 328;
UPDATE survey_store_districts SET store_name = 'Spokane Sullivan' WHERE store_num = 351;
UPDATE survey_store_districts SET store_name = 'South Salem' WHERE store_num = 355;
UPDATE survey_store_districts SET store_name = 'Stadium' WHERE store_num = 360;
UPDATE survey_store_districts SET store_name = 'The Dalles' WHERE store_num = 372;
UPDATE survey_store_districts SET store_name = 'Tigard' WHERE store_num = 375;
UPDATE survey_store_districts SET store_name = 'Tillamook' WHERE store_num = 377;
UPDATE survey_store_districts SET store_name = 'Twin Falls' WHERE store_num = 383;
UPDATE survey_store_districts SET store_name = 'Tacoma Stevens' WHERE store_num = 390;
UPDATE survey_store_districts SET store_name = 'Kirkland' WHERE store_num = 391;
UPDATE survey_store_districts SET store_name = 'Tualatin' WHERE store_num = 393;
UPDATE survey_store_districts SET store_name = 'West Eugene' WHERE store_num = 417;
UPDATE survey_store_districts SET store_name = 'South Hill' WHERE store_num = 424;
UPDATE survey_store_districts SET store_name = 'Boise-Five Mile' WHERE store_num = 439;
UPDATE survey_store_districts SET store_name = 'Idaho Glenwood' WHERE store_num = 449;
UPDATE survey_store_districts SET store_name = 'Bothell' WHERE store_num = 457;
UPDATE survey_store_districts SET store_name = 'Mill Creek' WHERE store_num = 458;
UPDATE survey_store_districts SET store_name = 'Renton' WHERE store_num = 459;
UPDATE survey_store_districts SET store_name = 'Salmon Creek' WHERE store_num = 460;
UPDATE survey_store_districts SET store_name = 'Scappoose' WHERE store_num = 462;
UPDATE survey_store_districts SET store_name = 'Florence' WHERE store_num = 464;
UPDATE survey_store_districts SET store_name = 'Walker Road' WHERE store_num = 482;
UPDATE survey_store_districts SET store_name = 'West Fairbanks' WHERE store_num = 485;
UPDATE survey_store_districts SET store_name = 'Yakima' WHERE store_num = 486;
UPDATE survey_store_districts SET store_name = 'Wilsonville' WHERE store_num = 516;
UPDATE survey_store_districts SET store_name = 'Hollywood West' WHERE store_num = 600;
UPDATE survey_store_districts SET store_name = 'Shelton' WHERE store_num = 603;
UPDATE survey_store_districts SET store_name = 'Bethel Station' WHERE store_num = 604;
UPDATE survey_store_districts SET store_name = 'James Center' WHERE store_num = 605;
UPDATE survey_store_districts SET store_name = 'Ballard' WHERE store_num = 608;
UPDATE survey_store_districts SET store_name = 'East Bench' WHERE store_num = 613;
UPDATE survey_store_districts SET store_name = 'Battle Ground' WHERE store_num = 614;
UPDATE survey_store_districts SET store_name = 'University Place' WHERE store_num = 615;
UPDATE survey_store_districts SET store_name = 'Palmer' WHERE store_num = 649;
UPDATE survey_store_districts SET store_name = 'Redmond, OR' WHERE store_num = 650;
UPDATE survey_store_districts SET store_name = 'Canby' WHERE store_num = 651;
UPDATE survey_store_districts SET store_name = 'Ellensburg' WHERE store_num = 652;
UPDATE survey_store_districts SET store_name = 'Wasilla' WHERE store_num = 653;
UPDATE survey_store_districts SET store_name = 'East Wenatchee' WHERE store_num = 654;
UPDATE survey_store_districts SET store_name = 'Port Orchard' WHERE store_num = 655;
UPDATE survey_store_districts SET store_name = 'Southeast Anchorage' WHERE store_num = 656;
UPDATE survey_store_districts SET store_name = 'Thor Street' WHERE store_num = 657;
UPDATE survey_store_districts SET store_name = 'Issaquah' WHERE store_num = 658;
UPDATE survey_store_districts SET store_name = 'Tumwater' WHERE store_num = 659;
UPDATE survey_store_districts SET store_name = 'Wood Village' WHERE store_num = 660;
UPDATE survey_store_districts SET store_name = 'Sunset' WHERE store_num = 661;
UPDATE survey_store_districts SET store_name = 'Boise-Franklin' WHERE store_num = 662;
UPDATE survey_store_districts SET store_name = 'Sandy' WHERE store_num = 663;
UPDATE survey_store_districts SET store_name = 'Sumner' WHERE store_num = 665;
UPDATE survey_store_districts SET store_name = 'North Bellingham' WHERE store_num = 667;
UPDATE survey_store_districts SET store_name = 'Chugiak-Eagle River' WHERE store_num = 668;
UPDATE survey_store_districts SET store_name = 'Snohomish' WHERE store_num = 681;
UPDATE survey_store_districts SET store_name = 'Maple Valley' WHERE store_num = 682;
UPDATE survey_store_districts SET store_name = 'Grand Central' WHERE store_num = 683;
UPDATE survey_store_districts SET store_name = 'Eagle Island' WHERE store_num = 685;
UPDATE survey_store_districts SET store_name = 'Alderwood' WHERE store_num = 688;
UPDATE survey_store_districts SET store_name = 'Gig Harbor' WHERE store_num = 691;
UPDATE survey_store_districts SET store_name = 'Happy Valley' WHERE store_num = 694;

-- Refresh active question set text with {{storeName}} placeholders
UPDATE survey_question_sets SET title = 'Division 701 — In-Store Best Practices Survey (v2)', spec = $qspec${"version": 2, "title": "Division 701 — In-Store Best Practices Survey (v2)", "sections": [{"id": "A", "title": "KOMPASS Cart & Storage", "questions": [{"id": "Q5", "text": "Does {{storeName}} have a KOMPASS cart?", "type": "choice", "options": ["Yes", "No", "Other"], "photo": true, "branches": [{"when": "Yes", "id": "Q5a", "text": "Does {{storeName}} put new items on it?", "type": "yesno", "good": "Yes"}, {"when": ["No", "Other"], "id": "Q5b", "text": "Does {{storeName}} have an area for storing KOMPASS supplies, data skins, pushers, and reset materials?", "type": "yesno", "good": "Yes"}], "good": "Yes"}, {"id": "Q6", "text": "Where at {{storeName}} is the cart or designated area located (if there is one)?", "type": "text", "photo": true, "placeholder": "Describe the location in enough detail that someone new could find it", "examples": ["In the back room, between Grocery Receiving and Home Side Receiving there is a door where you can turn left or right, turn right, and at the end of the HABA/HBC rows of u-boats, on the right hand side, you'll see the green Kompass cart with a white label on it."], "examplesLabel": "Example of the detail we need"}, {"id": "Q7", "text": "Does {{storeName}} have a KOMPASS Champion or reset captain?", "type": "yesno", "branches": [{"when": "Yes", "id": "Q7a", "text": "What is their name?", "type": "text"}, {"when": "Yes", "id": "Q7b", "text": "Do they keep the KOMPASS cart or area organized?", "type": "choice", "options": ["Yes", "No", "N/A"], "good": "Yes"}], "good": "Yes"}]}, {"id": "B", "title": "Supplies & Equipment", "questions": [{"id": "Q8", "text": "Does {{storeName}} have cleaning supplies available to use?", "type": "yesno", "good": "Yes"}, {"id": "Q9", "text": "Does {{storeName}} provide garbage/recycling bags?", "type": "yesno", "good": "Yes"}, {"id": "Q10", "text": "Does {{storeName}} supply easy access to step ladders and banana boxes?", "type": "yesno", "good": "Yes"}, {"id": "Q11", "text": "Is our team provided with adequate data skins/channel strips at {{storeName}} to replace broken or dirty ones?", "type": "yesno", "good": "Yes"}]}, {"id": "C", "title": "Staging Areas", "questions": [{"id": "Q12", "text": "Does {{storeName}} have a designated staging area for new shelf-stable grocery items?", "type": "yesno", "photo": true, "detailOn": "Yes", "detailPlaceholder": "Please explain / name", "detailExamples": ["On a pallet", "On the Kompass cart", "On a u-boat (non-Kompass)", "In a specific area in the department", "In the cooler/freezer"], "detailExamplesLabel": "Suggestions for where it is", "good": "Yes"}, {"id": "Q13", "text": "Does {{storeName}} have a designated staging area for refrigerated/frozen product?", "type": "yesno", "photo": true, "detailOn": "Yes", "detailPlaceholder": "Please explain / name", "detailExamples": ["On a pallet", "On the Kompass cart", "On a u-boat (non-Kompass)", "In a specific area in the department", "In the cooler/freezer"], "detailExamplesLabel": "Suggestions for where it is", "good": "Yes"}, {"id": "Q14", "text": "Does {{storeName}} have a designated staging area for natural foods items?", "type": "yesno", "photo": true, "detailOn": "Yes", "detailPlaceholder": "Please explain / name", "detailExamples": ["On a pallet", "On the Kompass cart", "On a u-boat (non-Kompass)", "In a specific area in the department", "In the cooler/freezer"], "detailExamplesLabel": "Suggestions for where it is", "good": "Yes"}, {"id": "Q15", "text": "Does {{storeName}} have a designated staging area for HABA?", "type": "yesno", "photo": true, "detailOn": "Yes", "detailPlaceholder": "Please explain / name", "detailExamples": ["On a pallet", "On the Kompass cart", "On a u-boat (non-Kompass)", "In a specific area in the department", "In the cooler/freezer"], "detailExamplesLabel": "Suggestions for where it is", "good": "Yes"}, {"id": "Q16", "text": "Does {{storeName}} have a designated staging area for produce?", "type": "yesno", "photo": true, "detailOn": "Yes", "detailPlaceholder": "Please explain / name", "detailExamples": ["On a pallet", "On the Kompass cart", "On a u-boat (non-Kompass)", "In a specific area in the department", "In the cooler/freezer"], "detailExamplesLabel": "Suggestions for where it is", "good": "Yes"}]}, {"id": "D", "title": "Vestcom & Tags", "questions": [{"id": "Q17", "text": "Is our team notified if the Vestcom box at {{storeName}} has been delayed or otherwise unavailable?", "type": "yesno", "good": "Yes"}, {"id": "Q18", "text": "Is our team informed if there are materials missing from the Vestcom box at {{storeName}}?", "type": "yesno", "good": "Yes"}, {"id": "Q19", "text": "Are our associates notified if {{storeName}} has not received all shelf strips and POGs for an upcoming reset?", "type": "yesno", "good": "Yes"}, {"id": "Q20", "text": "Where is the Vestcom box typically found at {{storeName}}?", "type": "text", "photo": true, "placeholder": "Where do you usually find the Vestcom box?", "examples": ["Price change room", "File Maintenance", "Kompass cart", "Receivers desk", "Manager office"], "examplesLabel": "Examples"}, {"id": "Q21", "text": "Where are the price tags typically found at {{storeName}}?", "type": "text", "photo": true, "placeholder": "Where do you usually find the price tags?", "examples": ["Price change room", "File Maintenance", "Kompass cart", "Receivers desk", "Manager office", "In a drawer", "On a shelf", "In a file divider", "In a file cabinet", "Under, on, or above a shelf"], "examplesLabel": "Examples"}, {"id": "Q22", "text": "Is there a regular issue with finding either the box or the tags at {{storeName}}?", "type": "yesno", "detailOn": "Yes", "detailPlaceholder": "Please explain / name", "good": "No"}, {"id": "Q23", "text": "Does {{storeName}} separate strips and/or tags prior to us performing the resets?", "type": "yesno", "good": "Yes"}]}, {"id": "E", "title": "Store Requests & Scope of Work", "questions": [{"id": "Q24", "text": "Does {{storeName}} have a specific way they want overstock or not-in-set items handled?", "type": "yesno", "detailOn": "Yes"}, {"id": "Q25", "text": "Does {{storeName}} ask our team to place backstock on the top stock rack?", "type": "yesno", "good": "No"}, {"id": "Q26", "text": "Does {{storeName}} ask us to rotate product and check for out-of-date items?", "type": "yesno", "good": "No"}, {"id": "Q27", "text": "Does {{storeName}} ask us to perform the marking down of items pulled from sets?", "type": "yesno", "good": "No"}, {"id": "Q28", "text": "Does {{storeName}} ask us to make missing tags?", "type": "yesno", "good": "No"}, {"id": "Q29", "text": "Does {{storeName}} ask us to clean fixtures in excess of what would be considered our normal scope of involvement?", "type": "yesno", "good": "No"}]}, {"id": "F", "title": "Store Access & Entry", "questions": [{"id": "Q30", "text": "How do you enter {{storeName}} each morning?", "type": "text"}, {"id": "Q31", "text": "Do you show up before the remainder of the team?", "type": "yesno", "branches": [{"when": "Yes", "id": "Q31a", "text": "How does the rest of the team enter {{storeName}}?", "type": "text"}]}, {"id": "Q32", "text": "Does anyone at {{storeName}} make it difficult to gain entry?", "type": "yesno", "detailOn": "Yes", "good": "No"}, {"id": "Q33", "text": "Do you sign in on the vendor log?", "type": "yesno", "good": "Yes"}]}, {"id": "G", "title": "Store Contacts", "questions": [{"id": "Q34", "text": "Do you know the name of the store director at {{storeName}}?", "type": "yesno", "detailOn": "Yes", "good": "Yes"}, {"id": "Q35", "text": "Do you know the name of the price changer at {{storeName}}?", "type": "yesno", "detailOn": "Yes", "good": "Yes"}, {"id": "Q36", "text": "Do you know the name of the grocery manager at {{storeName}}?", "type": "yesno", "detailOn": "Yes", "good": "Yes"}, {"id": "Q37", "text": "Do you know the name of the grocery receiver at {{storeName}}?", "type": "yesno", "detailOn": "Yes", "good": "Yes"}]}, {"id": "H", "title": "Department Relations", "questions": [{"id": "Q38", "text": "Do any of the following departments at {{storeName}} regularly push back on us performing resets?", "type": "multiselect", "options": ["Produce", "Deli", "Bakery", "Meat Department", "HABA", "Natural Foods", "Grocery", "Pharmacy", "GM", "Other", "None"], "good": "None"}]}, {"id": "I", "title": "Technology", "questions": [{"id": "Q39", "text": "Does {{storeName}} use DSL (Digital Shelf Labels)?", "type": "yesno", "branches": [{"when": "Yes", "id": "Q39a", "text": "Does our team get pushback from {{storeName}} regarding use of a handheld (Zebra)?", "type": "yesno", "good": "No"}]}, {"id": "Q40", "text": "Is the wifi at {{storeName}} acceptable for performing your job?", "type": "yesno", "detailOn": "No", "good": "Yes"}]}, {"id": "J", "title": "Completion & Sign-Out", "questions": [{"id": "Q41", "text": "When getting signed out at the end of the day, does someone from {{storeName}} walk the sets to confirm completion standards prior to signing us out?", "type": "yesno", "good": "Yes"}]}, {"id": "K", "title": "Safety & Final Comments", "questions": [{"id": "Q42", "text": "Are there any safety issues or consistent issues with anything or anyone at {{storeName}}?", "type": "yesno", "detailOn": "Yes", "good": "No"}, {"id": "Q43", "text": "Are there any comments or concerns you would like us to be aware of at {{storeName}}?", "type": "text", "optional": true}]}]}$qspec$::jsonb WHERE version = 2;

