#!/usr/bin/env python3
"""Generate migration to register all hydration-manifest stores in hub_stores."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "src" / "data"
FIXTURES_DIR = DATA_DIR / "hub-fixtures"
MANIFEST_JSON = DATA_DIR / "kroger-manifest-701-20260531.json"
SEED_PATH = DATA_DIR / "kompass-cycle-242292-seed.json"
MIGRATION_PATH = ROOT / "src" / "migrations" / "030_hydration_manifest_hub_stores.sql"

HYDRATION_DBKEY = "9007685"
HYDRATION_ACTION = "C082_V861_I021_MX"


def visit_id_for_store(store: int) -> int:
    return int("99999" + str(store).zfill(3)[-5:])


def load_seed_visit_ids() -> dict[int, int]:
    if not SEED_PATH.is_file():
        return {}
    seed = json.loads(SEED_PATH.read_text(encoding="utf-8"))
    out: dict[int, int] = {}
    for row in seed.get("stores") or []:
        vid = row.get("default_visit_id")
        if vid is not None:
            out[int(row["store_number"])] = int(vid)
    return out


def hydration_rows(store: int) -> list[str]:
    path = FIXTURES_DIR / f"{store}.json"
    if not path.is_file():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    lanes: list[str] = []
    seen: set[str] = set()
    for fixture in data.get("fixtures") or []:
        if fixture.get("dbkey") != HYDRATION_DBKEY and fixture.get("action") != HYDRATION_ACTION:
            continue
        name = (fixture.get("name") or "").upper()
        if "SUPER NATURAL" in name:
            continue
        lane = fixture.get("lane")
        if lane is None:
            continue
        lane_s = str(lane)
        if lane_s in seen:
            continue
        seen.add(lane_s)
        lanes.append(lane_s)
    return lanes


def sql_str(value) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def main() -> None:
    manifest = json.loads(MANIFEST_JSON.read_text(encoding="utf-8"))
    stores = sorted(
        int(store)
        for store, pogs in (manifest.get("checklanes_by_store") or {}).items()
        if HYDRATION_DBKEY in pogs
    )
    seed_visits = load_seed_visit_ids()

    lines = [
        "-- All FM stores on Kroger manifest with hydration POG 9007685.",
        "-- Generated by scripts/generate-hydration-manifest-migration.py",
        "",
    ]

    lines.append(f"-- Register {len(stores)} stores in hub_stores (idempotent).")
    for store in stores:
        name = f"FM {store}"
        lines.append(
            "INSERT INTO hub_stores (store_number, name, is_test) "
            f"VALUES ({sql_str(store)}, {sql_str(name)}, FALSE) "
            "ON CONFLICT (store_number) DO UPDATE "
            "SET name = COALESCE(NULLIF(hub_stores.name, ''), EXCLUDED.name);"
        )
    lines.append("")

    lines.append(f"-- Bootstrap hydration section_state ({HYDRATION_DBKEY}) per store visit.")
    for store in stores:
        lanes = hydration_rows(store)
        if not lanes:
            lines.append(f"-- SKIP store {store}: no hydration lane in hub-fixtures")
            continue
        visit_id = seed_visits.get(store) or visit_id_for_store(store)
        for lane in lanes:
            lines.append(
                "INSERT INTO section_state (visit_id, lane, dbkey, state) "
                f"VALUES ({visit_id}, {sql_str(lane)}, {sql_str(HYDRATION_DBKEY)}, 'not_started') "
                "ON CONFLICT (visit_id, lane, dbkey) DO NOTHING;"
            )

    MIGRATION_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {MIGRATION_PATH.name} for {len(stores)} stores")


if __name__ == "__main__":
    main()
