#!/usr/bin/env python3
"""Generate migration to register all hydration-manifest stores in hub_stores."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "src" / "data"
MANIFEST_JSON = DATA_DIR / "kroger-manifest-701-20260531.json"
MIGRATION_PATH = ROOT / "src" / "migrations" / "030_hydration_manifest_hub_stores.sql"

HYDRATION_DBKEY = "9007685"


def sql_str(value) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def main() -> None:
    manifest = json.loads(MANIFEST_JSON.read_text(encoding="utf-8"))
    stores = sorted(
        int(store)
        for store, pogs in (manifest.get("checklanes_by_store") or {}).items()
        if HYDRATION_DBKEY in pogs
    )

    lines = [
        "-- All FM stores on Kroger manifest with hydration POG 9007685.",
        "-- Generated by scripts/generate-hydration-manifest-migration.py",
        "",
        f"-- Register {len(stores)} stores in hub_stores (idempotent).",
    ]
    for store in stores:
        name = f"FM {store}"
        lines.append(
            "INSERT INTO hub_stores (store_number, name, is_test) "
            f"VALUES ({sql_str(store)}, {sql_str(name)}, FALSE) "
            "ON CONFLICT (store_number) DO UPDATE "
            "SET name = COALESCE(NULLIF(hub_stores.name, ''), EXCLUDED.name);"
        )
    lines.extend([
        "",
        "-- Live visit IDs and section_state come from sync-checklane-visits-from-prod.js (project 1715).",
        "",
    ])

    MIGRATION_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {MIGRATION_PATH.name} for {len(stores)} stores")


if __name__ == "__main__":
    main()
